[project]
name = "weave"
version = "0.1.0"
description = "We unlock energy data for everyone"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.8.8",
    "dagster-cloud>=1.8.8",
    "weave",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["weave_tests"]

[tool.dagster]
module_name = "weave.definitions"
code_location_name = "weave"

[tool.uv]
dev-dependencies = [
    "dagster-webserver>=1.8.8",
    "pytest>=8.3.3",
]

[tool.uv.sources]
dagster-log-processing = { workspace = true }
weave = { workspace = true }
